### ISSUE TITLE
Regression (1.2 - 1.8)

### ISSUE THREAD

**Issue by szkrd** [WebReflection/polpetta#2] opened 2012-07-20 08:06 UTC
Hi! I just updated to the current pushed version (1.8, from yesterday's 1.2 - wow, the versioning speed feels like firechrome:)) and the server stopped working (win-7). Chrome resets the url bar, firefox appends a backslash, but neither browser shows output, the console is empty.

(Btw I really don't know what utf8 character you choose for polpetta, but wherever it is, it's just a little empty square - maybe except on the little black screenshot, but nowhere else...)

**Comment by WebReflection** [comment] 2012-07-20 08:27
Damn it windows! Can you please check if forcing the SEP variable to "/"
solves? I'm off these days, can't quick fix neither test Win, sorry
On Jul 20, 2012 9:06 AM, "Szabolcs Kurdi" <
reply@reply.github.com>
wrote:

**Comment by szkrd** [comment] 2012-07-20 08:37
It doesn't fix it :( Maybe I'm wrong, but imo the path separator and the http uri separator are two very different things.

**Comment by WebReflection** [comment] 2012-07-20 08:40
Sure they are, that's why I have asked to change that.. left in but not
needed for redirect. Is the problem folder listing? Or no file works
anymore? Cause in Mac everything is ultra fine.
On Jul 20, 2012 10:37 AM, "Szabolcs Kurdi" <
reply@reply.github.com>
wrote:

**Comment by szkrd** [comment] 2012-07-20 09:13
Directory listing works. I think you should separate the uri separator and the FS separator and the code should be fine. 

Right now your resolver returns an empty string, because backslashes and slashes are mixed up (and src.indexOf(polpetta.root) will fail). Maybe it's none of my business, but an oldish windows xp image and a virtualbox would help with that "damn windows" :)

**Comment by WebReflection** [comment] 2012-07-20 09:20
I have an old neetbook for windows tests. Gonna fix and test this Sunday
night when I am back. Polpetta.root should be replaced via SEP and "/"
indeed and SEP can simply go. Apologies for the rushed push without tests
on Win7 , lesson learned. Also consider that the onload callback won't have
polpetta as "this" reference but as third parameter and for code/function
reusability  so please use var p = this; on top and wait for next update to
drop that line and use p as third argument. Cheers
On Jul 20, 2012 11:13 AM, "Szabolcs Kurdi" <
reply@reply.github.com>
wrote:

**Comment by szkrd** [comment] 2012-07-20 09:21
Thanks, looking forward to the new release :)

**Comment by WebReflection** [comment] 2012-07-23 18:48
considering that every unload function now has 3 arguments, where the third is polpetta itself, can you confirm now everything is fine in windows? Thanks

**Comment by szkrd** [comment] 2012-07-23 19:46
Everything works fine (dir index, file contents, njs parsing), but in chrome if I access the server via "localhost" weird things happen (empty page, chrome://newTab, previous webpage), 127.0.0.1 on the other hand works okay.

**Comment by WebReflection** [comment] 2012-07-23 20:15
OK, I close this regression bug then since Chrome on localhost should not have a thing to do with the path ... also my Chrome has no problems at all with localhost ( both Canary and normal Chrome ) ... is it chrome only? Btw, I have spot another issue with the path normalizer ... it works but it shouldn't ... lol, coming back soon, please let me know other questions, thanks!

**Comment by WebReflection** [comment] 2012-07-23 20:29
... now the path is properly normalize into system and web ... so, only Chrome issue with 0.2.1 ?

**Comment by szkrd** [comment] 2012-07-23 21:22
Yes, but srware iron and chromium nightly are fine, so I guess it's just a fluke.

**Comment by WebReflection** [comment] 2012-07-23 22:36
then is a won't fix. I close this bug, .htaccess is the next thing coming up ... the support for on staticfile seems to be OK and I have flagged 0.2.1 as stable but feel free to try 0.2.2 too. Thanks

**Closed as completed by WebReflection** 2012-07-23 22:36 UTC
